# render.yaml - Render Blueprints (Versão Final Simplificada)

# Define a infraestrutura: Banco de Dados e Serviço Web

services:
# 1. SERVIÇO DE BANCO DE DADOS (PSERV)
  - type: pserv
    name: identidade-db
    plan: free 
    
    # CRÍTICO: Define o local de montagem do disco para dados persistentes.
    disk:
      name: jornada-db-disk
      sizeGB: 1
      mountPath: /var/lib/postgresql/data # CAMINHO OBRIGATÓRIO

# 2. SERVIÇO WEB (BACKEND NODE/EXPRESS)
  - type: web
    name: identidade-api
    rootDir: backend # Pasta do seu código de API
    plan: free
    env: node
    
    # Comandos de construção
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
      
    # Comando de inicialização do servidor
    startCommand: node dist/server.js
    
    # Variáveis de Ambiente
    envVars:
      # CRUCIAL: O Render injeta a string de conexão do DB
      - key: DATABASE_URL
        fromDatabase:
          name: identidade-db
          property: connectionString
      # URL do Frontend para o CORS (ajustaremos no Passo 5)
      - key: FRONTEND_URL
        value: "AGUARDANDO_URL_FRONTEND" 
      # Porta que o seu server.ts irá usar
      - key: PORT
        value: 3000

    # Adiciona a migração (é necessário para o serviço web, não para o DB)
    preDeployCommand: npx prisma migrate deploy
